version: "3.8"

services:
  s3mock:
    image: adobe/s3mock:latest
    ports:
      - "9090:9090"
    environment:
      - initialBuckets=report-papers-local
      - root=/s3mock
    volumes:
      - ./data/s3mock:/s3mock

  aws-ses-local:
    image: ghcr.io/domdomegg/aws-ses-v2-local:latest
    ports:
      - "8005:8005"
    environment:
      - SES_PORT=8005
      - SES_HOST=0.0.0.0

  teams-webhook-mock:
    image: ghcr.io/tarampampam/webhook-tester:2
    ports:
      - "8006:8080"
